server:
  port: 9092

spring:
  application:
    name: 3party-app
    
  sleuth:
    sampler:
      probability: 1.0
  
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    sender:
      type: web
    service:
      name: 3party-app
      
      